"""Stage 10D: write outputs/01_EVIDENCE_MAP.csv (valid CSV, quoted)."""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "outputs" / "01_EVIDENCE_MAP.csv"

HEADER = ["question_id", "question", "answer_summary", "source_ids",
          "evidence_strength", "conflicts", "gaps"]

ROWS = [
    ["Q1",
     "Review at least 150 high-quality peer-reviewed papers spanning the advisor group's GaN/SiC/WBG device fields and relevant fusion, plasma, stellarator, magnetic-diagnostic, and instrumentation fields",
     "Done: 231 unique verified peer-reviewed sources (S0001-S0231) merged from three lanes, deduplicated by normalized DOI then title, with material coverage of every SOURCE_POLICY category (per-category row counts 59-133); 32 DOIs (~14%) independently re-verified at 10D via Crossref with 32/32 match.",
     "S0001-S0231 (full ledger); coverage counts in 01_SOURCE_COVERAGE.md",
     "strong",
     "Two same-DOI cross-lane duplicate pairs found and merged (A0068/B0041 -> S0068; A0070/B0054 -> S0070); Czech-diacritic author-name variants resolved against Crossref (S0070, S0120, S0121, S0122).",
     "75/231 rows are metadata_only (bibliographic identity verified, content not read); publisher paywalls (IEEE/AIP/Elsevier/Wiley) structurally limited full-text access to 23 rows."],
    ["Q2",
     "Is the original direction (GaN Hall-effect magnetic diagnostics for in-situ MCF measurement) publishable and strategically strong?",
     "Evidence assembled, decision deferred to stage 20_direction. Supporting: no GaN/AlGaN Hall sensor found deployed in any tokamak/stellarator across three independent lanes (novelty anchor); fusion Hall sensing is the field's own chosen steady-state answer (ITER bismuth array, JET InSb 11-yr record), so the sensing concept is validated; GaN offers temperature-stable sensitivity beyond InSb's ~150 C class limit. Opposing: device-level GaN Hall characterization is published prior art (largely from the advisor's own group), so novelty survives only at the application/deployment granularity; a GaN entrant lacks any fusion qualification data comparable to bismuth/antimony/InSb campaigns.",
     "S0004;S0005;S0006;S0012;S0016;S0066;S0067;S0068;S0069;S0070;S0112;S0113;S0114;S0117;S0118;S0120;S0121;S0122;S0143;S0153",
     "strong",
     "Reviewer 1 ('novel and unique') and Reviewer 2 ('not novel') are both literature-consistent at different claim granularities - application-context vs device-technique; the fork is framing, not evidence.",
     "Absence-of-evidence basis for the first-GaN-in-fusion claim (bounded search, found three times independently); no published success bar for a first-generation academic in-stellarator Hall sensor."],
    ["Q3",
     "Prefer paths minimizing new cleanroom work with defensible novelty in application, calibration, measurement architecture, simulation, analysis, inverse methods, or software",
     "Seven method classes have mature, citable precedent and are unapplied on HSX: (1) formal calibration/uncertainty (Bayesian, Allan variance, GUM/MC, traceability); (2) Kalman/Bayesian sensor fusion with HSX's existing diagnostics incl. a W7-AS stellarator precedent; (3) regularized inverse reconstruction; (4) ML/PINN equilibrium reconstruction (stellarator-class precedents exist; HSX-scale training data does not); (5) vector/array design + D-optimality placement for project 03; (6) reproducibility/device-to-device statistics; (7) first-deployment/qualification-as-contribution framing. Classes 1, 2, 6 need no new fabrication and no new campaign.",
     "S0051;S0158;S0159;S0160;S0161;S0164;S0165;S0167;S0168;S0171;S0179;S0180;S0181;S0187;S0188;S0189;S0192;S0193;S0194;S0197;S0199;S0208;S0210;S0214;S0216;S0217;S0218;S0219;S0220;S0221;S0222;S0223;S0225;S0226;S0227;S0229;S0230;S0231",
     "strong",
     "none",
     "No existing HSX discharge-magnetics database at the scale ML precedents trained on (KSTAR: 1118 discharges); no source quantifies the spatial/vector-coverage advantage of a 2-3 axis HSX probe over existing pickup belts."],
    ["Q4",
     "Review the submitted IEEE Sensors Letters manuscript, its source files, HSX data, and the 23-Jul-2026 decision/reviewer comments (literature dimension)",
     "Every decline-letter request maps to a published, citable norm: comparison table (assemblable from S0001-S0017 GaN rows + S0009/S0011/S0014 competitors - no existing review provides it); repeatability statistics (S0218 protocol; S0068's 19,000-pulse stability as the field's high bar); bench calibration (S0051/S0148 templates); bandwidth derivation (S0076 characterization norm); field-unit presentation (needs calibration). The 'first quasi-helically symmetric stellarator' phrasing should be corrected to Garcia 2025's exact wording 'first and only stellarator experiment optimized for quasi-helical symmetry' (S0128); Garren & Boozer (S0124) show exact QHS is impossible in principle.",
     "S0001;S0004;S0005;S0006;S0009;S0011;S0014;S0016;S0017;S0051;S0065;S0068;S0076;S0124;S0126;S0128;S0148;S0218",
     "strong",
     "Stage 00 conflict C1 stands: parent-project '2023, published' framing is contradicted by the supplied 2026 submission/decline records; no published record of the manuscript was found in this stage's searches.",
     "Figure-level reproduction of manuscript claims from raw HSX data was not attempted (Stage 00 checked file presence only)."],
    ["Q5",
     "Compare a revised Sensors Letters submission against arXiv preprint + substantially completed RSI study using the next HSX campaign (literature dimension)",
     "Evidence only, decision deferred to stages 20/30. Genre analysis of the ledger: RSI is its most frequent venue (29/231) and routinely publishes deployment+calibration+validation instrumentation work (stellarator in-vessel probes S0154, Hall deployments S0143/S0173, system-integration-as-contribution S0226); FED/Nucl. Fusion carry the Hall-sensor qualification lineage (S0148, S0068, S0112); short device-letter venues reward device novelty - the axis Reviewer 2 attacked. The advisor group has RSI precedent (S0006).",
     "S0006;S0068;S0093;S0112;S0143;S0148;S0154;S0173;S0226",
     "moderate",
     "none",
     "Preprints are excluded from the ledger by SOURCE_POLICY, so the arXiv half of the route comparison has no evidence base in this stage; venue decision requires the decline letter's resubmission terms (stage 30)."],
    ["Q6",
     "Specify the next experiment and analysis needed to close calibration, absolute-field, repeatability, uncertainty, bandwidth, conventional-probe-comparison, and novelty gaps (literature norms; plan itself is stage 40)",
     "The fusion-instrumentation validation norm is established: itemized uncertainty budgets, calibration against an independent standard/model, accuracy vs a stated requirement, environmental qualification as a program, and multi-pulse stability. Sub-rows Q6A-Q6G give per-gap norms.",
     "S0051;S0068;S0076;S0094;S0112;S0114;S0115;S0132;S0137;S0143;S0144;S0148;S0152;S0153;S0210;S0218;S0220",
     "strong",
     "none",
     "What accuracy/bandwidth/drift constitutes success for a first-generation academic device is not established by any source - nearest bars are ITER/JET-grade and may be an unfair target."],
    ["Q6A", "Absolute calibration and V_off closure",
     "Templates: traceable Hall-probe calibration with 5-term uncertainty budget (S0051); ITER OVSS campaign achieving ~2.5 mT calibration contribution against a 4 mT (2-sigma) requirement, 'at the limit of technical feasibility' (S0148); high-field Hall-coefficient fits with <0.11% error (S0115). Real-time attitude-independent bias estimation offers an in-situ algorithmic route (S0197).",
     "S0051;S0115;S0148;S0197", "strong", "none",
     "Project 02's bench emulator shows an unresolved ~109x magnitude anomaly (supplied fact, conflict C6); no calibration coefficient exists for Tim's sensor."],
    ["Q6B", "Absolute-field measurement in HSX",
     "Precedent paradigm: CTH's GaAs Hall array validated against Biot-Savart vacuum-field predictions (S0143); W7-X flux-surface mapping as the stellarator gold standard (S0137); HSX's own V3FIT-optimized diagnostic study defines the reconstruction context a calibrated point-field sensor would feed (S0132).",
     "S0132;S0137;S0143", "strong", "none",
     "No HSX vacuum-field-vs-Hall-sensor comparison exists; requires a calibrated sensor plus HSX field model access."],
    ["Q6C", "Repeatability / device-to-device statistics",
     "Norms: multi-geometry on-chip Hall-cell statistics (S0218); JET's 18-sensor +/-0.07% calibration stability over 19,000 pulses as the operational high bar (S0068); reproducibility-reporting agenda (S0221). AEIC explicitly requested repeatability across fabrication iterations (supplied fact C010).",
     "S0068;S0218;S0221", "strong", "none",
     "Only one module was tested per the decision letter; whether additional dies from the same run exist is NOT ESTABLISHED FROM SUPPLIED FILES."],
    ["Q6D", "Uncertainty budget",
     "Norms: EAST's itemized magnetics uncertainty budget (S0152); ITER Rogowski error modeling (S0094); GUM-vs-Monte-Carlo formal evaluation (S0220); Bayesian model-discrepancy separation (S0161); Allan-variance drift decomposition (S0168).",
     "S0094;S0152;S0161;S0168;S0220", "strong", "none", "none"],
    ["Q6E", "Bandwidth derivation and characterization",
     "Norm: swept characterization over the full band as in the 3-axis B-dot probe standard (10 kHz-50 MHz, S0076) and the RFX-mod2 digital chain (200 kHz, S0178); randomized-spinning readout preserving 2 MS/s Hall bandwidth shows the spinning/bandwidth trade-off is solvable (S0039). Reviewer 1 questioned the asserted 1 MHz figure (supplied fact C003).",
     "S0039;S0076;S0178", "strong", "none",
     "The manuscript's 1 MHz figure has no published derivation; a measured frequency-response curve for Tim's readout does not exist in supplied files."],
    ["Q6F", "Conventional-probe (B-dot/Mirnov) comparison",
     "The AEIC-requested comparison has abundant reference literature (B-dot design/calibration S0076; Mirnov array practice S0072/S0075; drift-limitation contrast S0104/S0107) and a direct paradigm precedent (S0143). The literature's mature answer is hybrid coil+Hall fusion (S0118, S0122), which reframes the comparison as complementarity, not competition.",
     "S0072;S0075;S0076;S0104;S0107;S0118;S0122;S0143", "strong", "none",
     "No co-located Hall-vs-B-dot measurement exists in supplied HSX data; requires a campaign measurement (stage 40)."],
    ["Q6G", "Novelty-gap closure and claim wording",
     "The defensible claim: first GaN/AlGaN (WBG 2DEG) Hall sensor in-vessel in any confinement device and first Hall sensor of any kind in a QHS stellarator (absence finding, three independent lanes); NOT 'first fusion Hall diagnostic' (20-year non-GaN lineage S0066-S0070, S0112-S0122). Facility claim must match S0128's exact wording. First-deployment framing is publishable when rigor-documented (S0225-S0231 precedent class).",
     "S0066;S0067;S0068;S0069;S0070;S0112;S0114;S0121;S0128;S0143;S0225;S0226;S0227;S0230",
     "strong",
     "Reviewer 1 vs Reviewer 2 novelty positions resolve at different claim granularities.",
     "Absence-of-evidence basis; a global prior-art guarantee is impossible from a bounded search."],
    ["Q7",
     "Screen concepts already supported by the supplied work for potentially protectable subject matter before public disclosure (research screen only)",
     "Literature-side input to stage 50: prior art is dense for spinning-current/offset methods (S0033-S0043, 1990s origin), fusion Hall-probe deployment (S0066-S0070, S0111-S0122), hybrid coil+Hall Kalman fusion (S0118, S0122), and 3-axis Hall architectures (S0027, S0032, S0208). Any protectable scope would need to be narrower than these; no legal conclusion is drawn here.",
     "S0027;S0032;S0033;S0038;S0041;S0066;S0068;S0112;S0114;S0118;S0122;S0208",
     "moderate",
     "none",
     "Patent literature itself was not searched at this stage (SOURCE_POLICY excludes patents from this ledger); stage 50 owns the prior-art screen."],
    ["Q8",
     "Produce a realistic 24-month PhD plan aligned with ~2-year graduation and startup preparation (literature dimension)",
     "Literature-side input to stage 60: campaign-uncoupled work (calibration/uncertainty, fusion with existing data, reproducibility - S0051/S0158-S0180/S0218-S0221) can proceed regardless of HSX schedule; campaign-coupled work (probe comparison, vector probe, ML reconstruction training data - S0143/S0210/S0181) is schedule-bound; the ITER/JET qualification programs (S0114, S0068) show multi-year timescales for full qualification, implying scope discipline for a 24-month window.",
     "S0051;S0068;S0114;S0143;S0181;S0210;S0218",
     "moderate",
     "none",
     "HSX campaign schedule commitments are NOT ESTABLISHED FROM SUPPLIED FILES; timeline construction is stage 60."],
]

with open(OUT, "w", encoding="utf-8", newline="") as fh:
    w = csv.writer(fh, quoting=csv.QUOTE_MINIMAL)
    w.writerow(HEADER)
    w.writerows(ROWS)

print(f"Wrote {len(ROWS)} rows to {OUT}")
