from pathlib import Path

from docx import Document


SOURCE = Path(
    r"D:\timzhao\Downloads\PhD_Career_Portfolio\01_PhD_Research\04_Magnetic_Sensor_Review_Sensors2026\.codex_tmp\advisor_abstract\advisor_changes_accepted.docx"
)
OUTPUT = Path(
    r"D:\timzhao\Downloads\sensor_review_paper_abstract_advisor_close_edit.docx"
)

ABSTRACT = (
    "Magnetic-field sensors enable non-invasive measurement of electrical current and magnetic "
    "fields generated by energy, transportation, and industrial systems, such as grid "
    "transformers, automotive drivetrains, and robotic motion-tracking systems. These sensors "
    "assess mechanical motion, material characteristics, and equipment condition for prediction, "
    "control, and forecasting, improving reliability and efficiency while reducing costs. A clear "
    "understanding of sensor operating principles, transduction mechanisms, and operational limits "
    "helps identify suitable applications and clarify each technology's technical value. In this "
    "review, we compare established and emerging magnetic-field sensing technologies and their "
    "integration with new artificial intelligence (AI) tools, relating performance and commercial "
    "maturity to representative applications across these domains. In addition, our review "
    "examines the implementation of data-driven methods in non-invasive magnetic-field sensing "
    "for real-time and in situ measurement, digital twins, and smart, adaptive, and reliable "
    "operation under realistic and dynamic conditions. This advanced sensing-system approach fully "
    "exploits each technology's strengths and improves measurement quality, system capability, and "
    "decision-making. Future progress will depend on integrating sensing hardware and computation "
    "while supporting traceability and compliance with relevant industry standards and government "
    "policy. By connecting sensing principles with application value and technology readiness, this "
    "detailed review provides a practical framework for magnetic-field sensing technology development "
    "and research."
)


def clear_runs(paragraph):
    for run in list(paragraph.runs):
        paragraph._element.remove(run._element)


def remove_paragraph(paragraph):
    element = paragraph._element
    element.getparent().remove(element)
    paragraph._p = paragraph._element = None


def main():
    doc = Document(SOURCE)

    label_index = next(
        i for i, paragraph in enumerate(doc.paragraphs)
        if paragraph.text.strip().startswith("Abstract (")
    )
    label = doc.paragraphs[label_index]
    abstract_paragraph = doc.paragraphs[label_index + 1]

    word_count = len(ABSTRACT.split())
    clear_runs(label)
    label.add_run(f"Abstract ({word_count} words):")

    clear_runs(abstract_paragraph)
    abstract_paragraph.add_run(ABSTRACT)

    for paragraph in list(doc.paragraphs[label_index + 2:]):
        if paragraph.text.strip():
            remove_paragraph(paragraph)

    doc.save(OUTPUT)
    print(f"Saved: {OUTPUT}")
    print(f"Abstract words: {word_count}")


if __name__ == "__main__":
    main()
